// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUm586XpLUVkwq9dPiDGbOh1Y_spkGL6s',
    appId: '1:899149622870:web:6803223058b9ce30db15f7',
    messagingSenderId: '899149622870',
    projectId: 'authtest-5021c',
    authDomain: 'authtest-5021c.firebaseapp.com',
    storageBucket: 'authtest-5021c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxRzHqviasguwUuuKhkuxImzenuwBe-q4',
    appId: '1:899149622870:android:23a0d6aae31208fcdb15f7',
    messagingSenderId: '899149622870',
    projectId: 'authtest-5021c',
    storageBucket: 'authtest-5021c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAolUzb1UO1vycnMOdn6wJYWyoUgfyGKRE',
    appId: '1:899149622870:ios:ade2cc41696a9bd9db15f7',
    messagingSenderId: '899149622870',
    projectId: 'authtest-5021c',
    storageBucket: 'authtest-5021c.appspot.com',
    iosBundleId: 'com.example.testeFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAolUzb1UO1vycnMOdn6wJYWyoUgfyGKRE',
    appId: '1:899149622870:ios:ade2cc41696a9bd9db15f7',
    messagingSenderId: '899149622870',
    projectId: 'authtest-5021c',
    storageBucket: 'authtest-5021c.appspot.com',
    iosBundleId: 'com.example.testeFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUm586XpLUVkwq9dPiDGbOh1Y_spkGL6s',
    appId: '1:899149622870:web:ace0699b8e4ccb93db15f7',
    messagingSenderId: '899149622870',
    projectId: 'authtest-5021c',
    authDomain: 'authtest-5021c.firebaseapp.com',
    storageBucket: 'authtest-5021c.appspot.com',
  );
}
